framework:
    messenger:
        buses:
            messenger.bus.default:
                middleware:
                    - doctrine_ping_connection
                    - doctrine_close_connection
                    - doctrine_transaction
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }

        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            sync: 'sync://'
            async_main_transport:
                dsn: '%env(MESSENGER_TRANSPORT_MAIN_DSN)%'
            async_position_transport:
                dsn: '%env(MESSENGER_TRANSPORT_POSITION_DSN)%'

        routing:
            'App\Message\PublisherParseMessage': sync
            'App\Message\PublisherErrorMessage': sync
            'App\Message\PublisherDeleteMessage': async_main_transport
            'App\Message\ApplicationDeleteMessage': sync
            'App\Message\ApplicationUpdateMessage': async_main_transport
            'App\Message\PositionParseMessage': sync #async_position_transport

