version: "2"

services:
    async_main_consumer:
        build: cli
        working_dir: /application
        volumes:
            - ../..:/application
            - /var/log/application:/application/var/log
        command: php -d memory_limit=4000M bin/console messenger:consume async_main_transport --limit=12 -vvv
        restart: always

